# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        activerecord: ['7.1', '7.2', '8.0']
        experimental: [false]
        exclude:
        - ruby: '2.7'
          activerecord: '7.2'
          experimental: false
        - ruby: '2.7'
          activerecord: '8.0'
          experimental: false
        - ruby: '3.0'
          activerecord: '7.2'
          experimental: false
        - ruby: '3.0'
          activerecord: '8.0'
          experimental: false
        - ruby: '3.1'
          activerecord: '8.0'
          experimental: false
    continue-on-error: ${{ matrix.experimental }}
    env:
      APPRAISAL: rails_${{ matrix.activerecord }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle install
        bundle exec appraisal $APPRAISAL bundle install
    - name: Run tests
      env:
        TZ: "Asia/Tokyo"
      run: bundle exec appraisal $APPRAISAL rake
